package br.edu.ifpb.apisinan.dto;

import br.edu.ifpb.apisinan.entities.Notificacao;

public final class NotificacaoMapper {

    private NotificacaoMapper() { }

    public static Notificacao toEntity(NotificacaoRequest r) {
        return new Notificacao(
                r.numero(),
                r.tipoNotificacao(),
                r.agravo(),
                r.codigoCid10(),
                r.dataNotificacao(),
                r.ufNotificacao(),
                r.municipioNotificacao(),
                r.codigoIbgeMunicipioNotificacao(),
                r.unidadeSaude(),
                r.codigoUnidadeSaude(),
                r.dataPrimeirosSintomas(),
                r.nomePaciente(),
                r.dataNascimento(),
                r.idade(),
                r.unidadeIdade(),
                r.sexo(),
                r.gestante(),
                r.racaCor(),
                r.escolaridade(),
                r.cartaoSus(),
                r.nomeMae(),
                r.ufResidencia(),
                r.municipioResidencia(),
                r.codigoIbgeMunicipioResidencia(),
                r.distritoResidencia(),
                r.bairroResidencia(),
                r.logradouro(),
                r.codigoLogradouro(),
                r.numeroResidencia(),
                r.complemento(),
                r.geoCampo1(),
                r.geoCampo2(),
                r.pontoReferencia(),
                r.cep(),
                r.telefone(),
                r.zona(),
                r.paisResidencia(),
                r.dataInvestigacao(),
                r.classificacaoFinal(),
                r.criterioConfirmacao(),
                r.casoAutoctone(),
                r.ufInfeccao(),
                r.paisInfeccao(),
                r.municipioInfeccao(),
                r.codigoIbgeMunicipioInfeccao(),
                r.distritoInfeccao(),
                r.bairroInfeccao(),
                r.doencaTrabalho(),
                r.evolucaoCaso(),
                r.dataObito(),
                r.dataEncerramento(),
                r.observacoes(),
                r.investigadorUnidade(),
                r.investigadorCodigoUnidade(),
                r.investigadorNome(),
                r.investigadorFuncao());
    }

    public static NotificacaoResponse toResponse(Notificacao n) {
        return new NotificacaoResponse(
                n.getId(),
                n.getNumero(),
                n.getTipoNotificacao(),
                n.getAgravo(),
                n.getCodigoCid10(),
                n.getDataNotificacao(),
                n.getUfNotificacao(),
                n.getMunicipioNotificacao(),
                n.getCodigoIbgeMunicipioNotificacao(),
                n.getUnidadeSaude(),
                n.getCodigoUnidadeSaude(),
                n.getDataPrimeirosSintomas(),
                n.getNomePaciente(),
                n.getDataNascimento(),
                n.getIdade(),
                n.getUnidadeIdade(),
                n.getSexo(),
                n.getGestante(),
                n.getRacaCor(),
                n.getEscolaridade(),
                n.getCartaoSus(),
                n.getNomeMae(),
                n.getUfResidencia(),
                n.getMunicipioResidencia(),
                n.getCodigoIbgeMunicipioResidencia(),
                n.getDistritoResidencia(),
                n.getBairroResidencia(),
                n.getLogradouro(),
                n.getCodigoLogradouro(),
                n.getNumeroResidencia(),
                n.getComplemento(),
                n.getGeoCampo1(),
                n.getGeoCampo2(),
                n.getPontoReferencia(),
                n.getCep(),
                n.getTelefone(),
                n.getZona(),
                n.getPaisResidencia(),
                n.getDataInvestigacao(),
                n.getClassificacaoFinal(),
                n.getCriterioConfirmacao(),
                n.getCasoAutoctone(),
                n.getUfInfeccao(),
                n.getPaisInfeccao(),
                n.getMunicipioInfeccao(),
                n.getCodigoIbgeMunicipioInfeccao(),
                n.getDistritoInfeccao(),
                n.getBairroInfeccao(),
                n.getDoencaTrabalho(),
                n.getEvolucaoCaso(),
                n.getDataObito(),
                n.getDataEncerramento(),
                n.getObservacoes(),
                n.getInvestigadorUnidade(),
                n.getInvestigadorCodigoUnidade(),
                n.getInvestigadorNome(),
                n.getInvestigadorFuncao());
    }

    public static NotificacaoResumo toResumo(Notificacao n) {
        return new NotificacaoResumo(
                n.getId(), n.getNumero(), n.getAgravo(), n.getDataNotificacao(), n.getNomePaciente(),
                n.getDataNascimento(), n.getNomeMae(), n.getSexo(), n.getMunicipioResidencia(),
                n.getUfResidencia(), n.getClassificacaoFinal(), n.getEvolucaoCaso());
    }
}

